- name: "Ensure the existence of an Operating System (provide default values)"
  redhat.satellite.operatingsystem:
    server_url: "{{ satellite_server }}"
    username: "{{ username }}"
    password: "{{ password }}"
    name: "RedHat"
    family: "{{ item.family }}"
    major: "{{ item.release }}"
    minor: "{{ item.release_ver }}"
    architectures: "{{ item.arch }}"
    password_hash: SHA256
    parameters: 
      - name: "ansible_python_interpreter"
        value: "/usr/libexec/platform-python"
  with_items: "{{ operating_systems }}"
